---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: check-toml
          - id: fix-encoding-pragma
          - id: forbid-submodules
          - id: mixed-line-ending
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.9.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: script-must-not-have-extension
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.31.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.1
      hooks:
          - id: forbid-tabs
    - repo: https://github.com/jackdewinter/pymarkdown
      rev: v0.9.9
      hooks:
          - id: pymarkdown
    - repo: local
      hooks:
          - id: black
            name: black
            entry: black . --check
            language: python
            types: [python]
          - id: ruff
            name: ruff
            entry: ruff check .
            language: python
            types: [python]
